#!/bin/bash

# ha_proxy script location
echo 'ha_proxy_path_configured = "/home/ubuntu/my-opsSchool/percona/terraform/scripts/percona_install"' >> /home/ubuntu/my-opsSchool/percona/terraform/variables


