---
- name: create user, add repo, install and configure ntp
  hosts: ?
  remote_user: ec2-user
  become: yes
  vars_files: ['credentials.yml']
  
  tasks:
  - name: create opsschool user
    user: name=opsschool password={{user_default_password}}
  