#!/bin/bash

## cloning git repo
cd /home/ubuntu
git clone https://github.com/L1nuxProdigy/my-opsSchool
mkdir /opt

## percona
cd /opt
wget  https://www.percona.com/downloads/Percona-Server-5.7/Percona-Server-5.7.24-27/binary/debian/trusty/x86_64/percona-server-client-5.7_5.7.24-27-1.trusty_amd64.deb
wget  https://www.percona.com/downloads/Percona-Server-5.7/Percona-Server-5.7.24-27/binary/debian/trusty/x86_64/percona-server-common-5.7_5.7.24-27-1.trusty_amd64.deb
wget  https://www.percona.com/downloads/Percona-Server-5.7/Percona-Server-5.7.24-27/binary/debian/trusty/x86_64/percona-server-server-5.7_5.7.24-27-1.trusty_amd64.deb
wget  https://www.percona.com/downloads/Percona-Server-5.7/Percona-Server-5.7.24-27/binary/debian/trusty/x86_64/libperconaserverclient20_5.7.24-27-1.trusty_amd64.deb

apt-get update -y
apt-get install mysql-common -y
apt-get install debsums -y
apt-get install libaio1 -y
apt-get install libmecab2 -y
dpkg -i /opt/percona-server-common-5.7_5.7.24-27-1.trusty_amd64.deb
dpkg -i /opt/percona-server-client-5.7_5.7.24-27-1.trusty_amd64.deb
dpkg -i /opt/libperconaserverclient20_5.7.24-27-1.trusty_amd64.deb
export DEBIAN_FRONTEND=noninteractive;
dpkg -i /opt/percona-server-server-5.7_5.7.24-27-1.trusty_amd64.deb

systemctl start mysql
mysql <  /home/ubuntu/my-opsSchool/percona/mysql_Session1_pre/mysqlsampledatabase.sql


