#!/bin/bash

## cloning git repo
cd /home/ubuntu
git clone https://github.com/L1nuxProdigy/my-opsSchool
mkdir /opt
cd /opt
wget https://repo.percona.com/apt/percona-release_latest.$(lsb_release -sc)_all.deb
sudo dpkg -i percona-release_latest.$(lsb_release -sc)_all.deb
apt update -y

sudo apt-get install percona-server-server-5.7 -y
cd /home/ubuntu
git clone https://github.com/L1nuxProdigy/my-opsSchool
systemctl start mysql
mysql <  /home/ubuntu/my-opsSchool/percona/mysqlsampledatabase.sql


