#!/bin/bash

## install grafana
wget https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb
sudo apt-get install -y adduser libfontconfig
sudo dpkg -i grafana_5.4.2_amd64.deb

# sudo service grafana-server start

sudo systemctl daemon-reload
sudo systemctl start grafana-server
sudo systemctl status grafana-server


