#!/bin/bash

### Consul Stuff ###
# Downloading and installing Prerequisites
sudo apt install unzip -y
sudo wget https://releases.hashicorp.com/consul/1.4.0/consul_1.4.0_linux_amd64.zip

# Unzipping and moving the binary to path
sudo unzip consul_1.4.0_linux_amd64.zip
sudo mv ./consul /usr/local/bin/consul
sudo chown ubuntu /usr/local/bin/consul


## consul client command
sudo mkdir /var/lib/consul /etc/consul.d
LOCAL_IPV4=$(curl "http://169.254.169.254/latest/meta-data/local-ipv4")

cat << EOCCF >/etc/consul.d/agent.hcl
node_name = "grafana"
client_addr =  "0.0.0.0"
recursors =  ["127.0.0.1"]
bootstrap =  false
datacenter = "dc1"
data_dir = "/var/lib/consul"
enable_syslog = true
log_level = "DEBUG"
retry_join = ["provider=aws tag_key=Name tag_value=Consul_Prometheus_by_Terraform"]
advertise_addr = "${LOCAL_IPV4}"
EOCCF

cat << EOCSU >/etc/systemd/system/consul.service
[Unit]
Description=consul agent
Requires=network-online.target
After=network-online.target
[Service]
LimitNOFILE=65536
Restart=on-failure
ExecStart=/usr/local/bin/consul agent -config-dir /etc/consul.d
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=SIGINT
Type=notify
[Install]
WantedBy=multi-user.target
EOCSU

systemctl daemon-reload
systemctl start consul &

## install grafana
wget https://dl.grafana.com/oss/release/grafana_5.4.2_amd64.deb
sudo apt-get install -y adduser libfontconfig
sudo dpkg -i grafana_5.4.2_amd64.deb

## finding the consul_prometheus_server private ip
while [[ $(consul members | head -n3 | wc -l | bc) < 3 ]]; do
        sleep 4
done

x=$(dig @127.0.0.1 -p 8600 consul_server.node.consul +noall +answer | tail -n1)
x2=${x# }
x3=$(echo $x2 | cut -d ' ' -f5)

# adding the consul_prometheus_server as a datasource
echo "apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${x3}:9090
" > /etc/grafana/provisioning/datasources/prometheus.yml

# adding the dashboard configuration
echo "apiVersion: 1

providers:
- name: 'Prometheus'
  orgId: 1
  folder: ''
  type: file
  disableDeletion: false
  editable: true
  options:
    path: /etc/grafana/provisioning/dashboards/dashboard.json
" > /etc/grafana/provisioning/dashboards/all.yml

# cloning the repo from git
cd /home/ubuntu
git clone https://github.com/L1nuxProdigy/my-opsSchool

# adding the dashboard json
cp /home/ubuntu/my-opsSchool/middle_project/grafana/json/dashboard.json /etc/grafana/provisioning/dashboards/dashboard.json

# starting the grafana service
sudo systemctl daemon-reload
sudo systemctl start grafana-server

## checking if grafana is up- wonky way
#lines_in_page=$(curl 'http://'${LOCAL_IPV4}':3000' | wc -l)
#while [[ $lines_in_page = 0 ]]; do
	#sleep 15
	#lines_in_page=$(curl 'http://'${LOCAL_IPV4}':3000' | wc -l)
done