servers=[
{
  :hostname => "opsschool-v",
  :ip => "192.168.100.10",
  :box => "ubuntu/trusty64",
  :ram => 1024,
  :cpu => 1,
  :provisions => ["install-percona.sh","editmycnf.sh"]
}
]
Vagrant.configure(2) do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
        machine [:provisions].each do |script|
           node.vm.provision "file", source: "mycnf.txt", destination: "/home/vagrant/mycnf.txt"	
	   node.vm.provision :shell, :path => script
        end
      node.vm.box = machine[:box]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.memory = machine[:ram]
        vb.cpus = machine[:cpu]
      end
    end
  end
end
