#!/bin/bash

### Consul Stuff ###
# Downloading and installing Prerequisites
sudo apt install unzip -y
sudo wget https://releases.hashicorp.com/consul/1.4.0/consul_1.4.0_linux_amd64.zip

# Unzipping and moving the binary to path
sudo unzip consul_1.4.0_linux_amd64.zip
sudo mv ./consul /usr/local/bin/consul
sudo chown ubuntu /usr/local/bin/consul


## consul client command
sudo mkdir /var/lib/consul /etc/consul.d
LOCAL_IPV4=$(curl "http://169.254.169.254/latest/meta-data/local-ipv4")

cat << EOCCF >/etc/consul.d/agent.hcl
node_name = "kibana"
client_addr =  "0.0.0.0"
recursors =  ["127.0.0.1"]
bootstrap =  false
datacenter = "dc1"
data_dir = "/var/lib/consul"
enable_syslog = true
log_level = "DEBUG"
retry_join = ["provider=aws tag_key=Name tag_value=Consul_Prometheus_by_Terraform"]
advertise_addr = "${LOCAL_IPV4}"
EOCCF

cat << EOCSU >/etc/systemd/system/consul.service
[Unit]
Description=consul agent
Requires=network-online.target
After=network-online.target
[Service]
LimitNOFILE=65536
Restart=on-failure
ExecStart=/usr/local/bin/consul agent -config-dir /etc/consul.d
ExecReload=/bin/kill -HUP $MAINPID
KillSignal=SIGINT
Type=notify
[Install]
WantedBy=multi-user.target
EOCSU

systemctl daemon-reload
systemctl start consul &

## kibana prerequisites- JAVA
sudo add-apt-repository ppa:openjdk-r/ppa -y
sudo apt-get update -y
sudo apt-get install openjdk-8-jdk-headless -y

## kibana install
wget https://artifacts.elastic.co/downloads/kibana/kibana-6.5.4-amd64.deb
dpkg -i kibana-6.5.4-amd64.deb

# setting an interactive shell variable named x3 as a local ip for a consul node
x=$(dig @127.0.0.1 -p 8600 elasticsearch.node.consul +noall +answer | tail -n1)
x2=${x# }
x3=$(echo $x2 | cut -d ' ' -f5)

## finding the elastic_search private ip
while [[ ${#x3} = 0 ]]; do
        sleep 15
		x=$(dig @127.0.0.1 -p 8600 elasticsearch.node.consul +noall +answer | tail -n1)
		x2=${x# }
		x3=$(echo $x2 | cut -d ' ' -f5)
done

## kibana configuration
echo 'elasticsearch.url: "http://'${x3}':9200"' >> /etc/kibana/kibana.yml
echo 'server.host: "'$LOCAL_IPV4'"' >> /etc/kibana/kibana.yml

systemctl enable kibana
systemctl start kibana

cd /home/ubuntu
git clone https://github.com/L1nuxProdigy/my-opsSchool

## checking if kibana is up- wonky way
lines_in_page=$(curl 'http://'${LOCAL_IPV4}':5601/app/kibana#/management/kibana/objects?_g=()' | wc -l)
while [[ $lines_in_page = 0 ]]; do
	sleep 15
	lines_in_page=$(curl 'http://'${LOCAL_IPV4}':5601/app/kibana#/management/kibana/objects?_g=()' | wc -l)
done
## creating filebeat index-patternt
cd /home/ubuntu/my-opsSchool/middle_project/ELK/json
./kibana_script_for_all_curls

